---
title: "Draft Fig3 Plots"
format: html
editor: visual
---

# Libraries

```{r}
library(tidyverse)
```

```{r}
# Test dataset
test_set <- data.frame(
  Gene = c("GeneA", "GeneB", "GeneC", "GeneD", "GeneE", "GeneF", "GeneG", "GeneH","GeneQ", "Gene1", "Gene2", "Gene3", "Gene4", "Gene5", "Gene6","Gene7"),
  Species = c("Human", "Human", "Monkey", "Monkey", "Monkey", "Monkey","Human","Human","Monkey","Monkey","Human","Monkey","Chimp","Chimp","Chimp","Chimp"),
  Association = c("Neotenic", "Neotenic", "Neotenic", "Accelerated", "Neotenic", "Accelerated", "Accelerated", "Accelerated", "Accelerated","Neotenic","Neotenic", "Accelerated", "Neotenic", "Accelerated", "Neotenic","Accelerated"),
  Tissue = c("Forebrain", "Forebrain", "Forebrain", "Midbrain", "Forebrain", "Midbrain", "Forebrain", "Midbrain", "Midbrain", "Midbrain", "Midbrain", "Forebrain","Midbrain","Forebrain","Forebrain","Midbrain")
)

# Display the dataset
print(test_set)
```

# Figure 3A

The distribution of neotenic and accelerated genes between brain tissue from the prefrontal cortex for humans, chimps and macaque, additionally for brain tissue caudate nucleus (human only).

```{r}
# Condence to a new dataset with % caragory
percent_phyloontogenic <- test_set |>
  group_by(Species, Association, Tissue) |>
  summarise(Count = n()) |>
  mutate(Percentage = (Count / sum(Count))*100)

print(percent_phyloontogenic)
```

```{r}

#| label: Phyloontogentic_plot1


ggplot(data = percent_phyloontogenic,
       mapping = aes(y= Species,
                     x= Percentage,
                     fill = Association)) +
  geom_bar(stat = "identity",
           position=position_dodge(),
           color = "black") +
  scale_fill_manual(values = c("red","blue"),
                    labels = c("Accelerated","Neotenic"))+
    facet_wrap(~Tissue) +
  theme_minimal() +
  theme(legend.position="none",
        plot.title.position = "plot",
        plot.subtitle = element_textbox_simple(),
        text=element_text(size=12,  family="momo"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) +
  labs(title = "Gene Distribution", 
       subtitle = "by Phyloontogentic Catagories: <span style='color:#ff0000'>Accelerated</span> vs. <span style='color:#0000FF'>Neotenic</span>",
       y = NULL,
       x = "Genes Assigned to Categories (%)")
```

# Figure 3B

The proportion of gray-matter-specific genes among human-neotenic genes and 'other', by tissue type (caudate nucleus, prefrontal cortex)

```{r}
# Condence to a new dataset with % grey matter genes caragory
percent_grey <- test_set |>
  filter(Species == "Human") |>
  group_by(Association, Tissue) |>
  summarise(Count = n()) |>
  mutate(Percentage = (Count / sum(Count))*100)

print(percent_grey)
```

```{r}
ggplot(data = percent_grey,
       mapping = aes(y= Tissue,
                     x= Percentage,
                     fill = Association)) +
  geom_bar(stat = "identity",
           position=position_dodge(),
           color = "black") +
  scale_fill_manual(values = c("red","blue"),
                    labels = c("Accelerated","Neotenic"))+
  theme_minimal() +
  theme(legend.position="none",
        plot.title.position = "plot",
        plot.subtitle = element_textbox_simple(),
        text=element_text(size=12,  family="momo"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) +
  labs(title = "Proportion of Gray-Matter-Specific Genes", 
       subtitle = "by Phyloontogentic Catagories: <span style='color:#ff0000'>Accelerated</span> vs. <span style='color:#0000FF'>Neotenic</span>",
       y = NULL,
       x = "%")
```
