---
title: "Principle Component Analysis"
output: html
output-dir: results
execute:
  echo: true
---

```{r}
#| output: false

library("tidyverse")
library("broom")
```

```{r}
#| output: false

# Set path for processed data directory
processed_data_dir <- file.path("..","data")

# Load the dataset
data <- read_tsv(file = file.path(processed_data_dir,
                                         "03_dat_joined.tsv"))
```

```{r}
#| output: false

# Select numeric columns (gene expression)
pca_data <- data |> 
  dplyr::select(where(is.numeric))

# Scale gene expression (variance = 1)
pca_data_scaled <- pca_data |>
  scale()

# Perform PCA on scaled gene expression data
pca_results <- pca_data_scaled |>
  prcomp(scale. = FALSE)
```

```{r}
#| output: false

# Combine PCA results with metadata
pca_results_df <- pca_results |>
  pluck("x") |>
  as_tibble() |>
  mutate(species = data |>
           pull(species),
         age = data |>
           pull(age))
```

```{r}
# Plot PCA results
pca_results_df |> 
  ggplot(aes(x = PC1,
             y = PC2,
             color = species,
             size = age)) +
  geom_point(alpha = 0.5) +
  labs(title = "Principle component analysis", 
       x = "PC1 (Age Correlation)", 
       y = "PC2 (Species Correlation)") +
  theme_minimal()

```
